name: pet_fit
description: Pet-Fit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  uuid: ^3.0.7
  expressions: ^0.2.5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  dio: ^4.0.4
  connectivity_plus: ^2.2.0
  provider: ^6.0.0
  google_fonts: ^2.0.0
  rive: ^0.7.16
  http: ^0.13.0
  image_picker: ^0.8.4+2
  open_filex: ^3.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  device_preview: ^1.1.0
  animate_do: ^3.0.2
  flutter_email_sender: ^5.2.0
  material_floating_search_bar: ^0.3.0
  shared_preferences: ^2.0.15
  webviewx: ^0.2.2
  flutter_card_swipper: ^0.4.0
  multi_image_picker: ^4.8.0
  permission_handler: ^9.0.1
  reorderable_grid_view: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0
build_runner: ^2.4.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/petlogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/petlogo.png"
    background_color: "#6e08de"
    theme_color: "#6e08de"
  windows:
    generate: true
    image_path: "assets/images/petlogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/petlogo.png"




flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/demo/
   - assets/RiveAssets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

